spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_lab_2
    password: hits
    username: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8191
