spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5432/testing_lab_2
    password: hits
    user: hits

  datasource:
    url: jdbc:postgresql://localhost:5432/testing_lab_2
    password: hits
    username: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8191
